### ISSUE TITLE
Add conformance tests

### ISSUE THREAD

**Issue by mbrubeck** [servo/unicode-bidi#1]
The Unicode consortium has a suite of conformance tests for the bidirectional algorithm, which can be found at:
- http://www.unicode.org/Public/UNIDATA/BidiTest.txt
- http://www.unicode.org/Public/UNIDATA/BidiCharacterTest.txt

We should add code to `tools/generate.py` to download these files and generate Rust unit tests for each of the test cases here.

**Comment by vicky-katara** [comment]
@mbrubeck , I am working on generating Rust unit test cases from BidiCharacterTest.txt, and the test cases essentially use the Fields 0(input string) and 4(output indices converted to output strings) and form unit test cases of the form "assert_eq!(reorder('input'), 'output');". Could you confirm whether this is correct? I am ignoring the levels information in the test cases since those should essentially be taken care of by the implementation.

Thanks!

**Comment by mbrubeck** [comment]
Yes, this sounds good.  Checking the levels may be useful too in some
cases, but just checking the output is the most improtant part.

**Comment by vicky-katara** [comment]
@mbrubeck, thanks for the confirmation. I had a followup question to the main issue. Since the files BidiTest.txt and BidiCharacterTest.txt are live, we will have to parse them each time, and delete the automated test cases added previously to lib.rs, and add the new ones, right?

**Comment by mbrubeck** [comment]
We should re-parse and re-generate the test cases only if someone manually runs the script to do it.  See [this discussion](https://github.com/servo/unicode-bidi/pull/19#issuecomment-156556302) for more details.

**Comment by vicky-katara** [comment]
Got it!

Thanks a lot!

**Comment by vicky-katara** [comment]
@mbrubeck, should we add the python code for insertion of the test cases into a new python file, or should we add code to generate.py?

**Comment by mbrubeck** [comment]
Either way is okay with me. If it's a lot of code (more than a handful of short functions), a separate file would probably be more readable.  `generate.py` could import the other file.

**Comment by vicky-katara** [comment]
Combined with the code for deletion of existing test cases, it comes out to about 150 lines of code...

We'll move it to another file. Thanks @mbrubeck

**Comment by samrudhisharma** [comment]
@mbrubeck - Is it possible for us to have a Hangouts session or for us to call you? We have some doubts regarding the steps we have to implement as well as this step.

**Comment by mbrubeck** [comment]
@samrudhisharma Sure, if you're available sometime today. You can find me in #servo on irc.mozilla.org to arrange a time, or just try calling +Matt Brubeck on Google Hangouts.
