### ISSUE TITLE
[RFE] Provide an API to explicitly process a single paragraph

### ISSUE THREAD

**Issue by jfkthame** [servo/unicode-bidi#114]
Clients that have already divided text into paragraphs could use a more efficient API that does not split on paragraph separators, and only has to return a single paragraph record rather than a vector.

@Manishearth Is this something you would be open to adding as a new API? (Exact name etc TBD...)

**Comment by Manishearth** [comment]
Open to it if it can be done with minimal maintenance burden and documented well; it's already somewhat hard to figure out how these APIs are to be used.

Perhaps post an idea of what you think the api would look like first?

**Comment by Manishearth** [comment]
I guess that's fine. I was hoping this could be done with a single API addition, but I guess it can't. If our fields weren't public I would have suggested we make the paragraphs field of BidiInfo a SmallVec and just use the same API.

Yeah, this is fine, when writing the duplicate APIs please add comments saying that they should be kept mostly in sync with the other ones.

**Comment by jfkthame** [comment]
This was done in #115.
