### ISSUE TITLE
Missing tags for versions 0.3.13 and 0.3.15

### ISSUE THREAD

**Issue by paolobarbolini** [servo/unicode-bidi#134]
While scanning through my dependencies I've discovered the tags for releases 0.3.13 and 0.3.15 to be missing. Could those be added to the git repo? The exact commit id can be found from:

* https://docs.rs/crate/unicode-bidi/0.3.13/source/.cargo_vcs_info.json
* https://docs.rs/crate/unicode-bidi/0.3.15/source/.cargo_vcs_info.json

**Comment by Manishearth** [comment]
Fixed, thanks!
