### ISSUE TITLE
Move away from travis

### ISSUE THREAD

**Issue by jrmuizel** [servo/unicode-bidi#60]
unicode-bidi is the largest user of servo's Travis credits. It doesn't seem like there's anything particular about unicode-bidi's CI that requires Travis so it would probably be good to move to something like github actions. This will preserve the credits for corefoundation-rs which needs the wide range of macOS versions that Travis supports.

**Comment by Manishearth** [comment]
I don't have time to do this soon but if someone else can do it I'd merge the PR and do the work of disabling travis

**Comment by jdm** [comment]
Also all of Servo's free travis ci credits are used up, so nothing can merge right now that depends on travis runs completing.
